
/*点击添加按钮操作*/
$("#debtPlus").on("click",function(){
	$("#addDebt").show(500);
	$("#debt_add1").removeAttr("readonly");
	$("#debt_add1").removeClass("text-get");
	/*聚焦操作*/
	$("#debt_add1").focus();
})
/*取消操作*/
$("#btnDebtCancel").on("click",function(){
	/*隐藏弹出框*/
	$("#addDebt").hide(500);
	/*清空弹出框*/
	$("#debt_add1").val("");
	$("#debt_add2").val("");
	$("#debtTips").text("");
	/*恢复正常隐藏*/
	hideORshow3();
})
